AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'This stack will create a paypal secrets stack encrypted using the kms key stacks kms key'

Resources:
   SpotJobsSecrets:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: spotjobs/paypal
      Description: paypal secrets
      KmsKeyId: 
        Fn::ImportValue: 
          !Sub "${AWS::AccountId}-${AWS::Region}-atomx-kms-key-arn"
      SecretString: '{
      "PAYPAL_CLIENT_ID":"AeHnmhm-4GSyV2w8r_0exteoKFZmMHutrpU5Rz_-ns92CwI22gAVCzy72_1PcpyXRXzOiqpPpEWCScRs",
      "PAYPAL_CLIENT_SECRET":"ECtcszIKlCcbd-r-4Ymg6GqMVpbl48kbA9UdBWaxgqrSLJBEaGZB30x3kR6R8WBwe02p1REaYLSx_4Tu"

      }'
      