AWSTemplateFormatVersion: '2010-09-09'
Description: create an s3 bucket

Parameters:
  ProjectPrefix:
    Type: String
    Description: The Projects prefix (dev/prod)

  BucketName:
    Type: String
    Description: The Bucket name

  Versioning:
    Type: String
    Description: Should this bucket to enable versioning (Enabled / Suspended)
    AllowedValues:
      - Enabled
      - Suspended

  ObjectExpirationInDays:
    Type: String
    Description: The number of days before the Oject is expired, this causes amazon to remove the object (automatic Cleanup)
    Default: 2555

  TransitionDaysForIA:
    Type: String
    Description: The number of days number of days before the object is moved to infrequently accessed storage
    Default: 90

  TransitionDaysForGlacier:
    Type: String
    Description: The number of days number of days before the object is moved to aws Glacier storage (based on object creation date)
    Default: 180



Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub ${ProjectPrefix}-${BucketName}-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: !Sub ${Versioning}
      LifecycleConfiguration:
        Rules:
          - Id: IA Rule
            Prefix: IA
            Status: Enabled
            ExpirationInDays: !Ref ObjectExpirationInDays
            Transition:
              TransitionInDays: !Ref TransitionDaysForGlacier
              StorageClass: Glacier
          - Id: Glacier Rule
            Prefix: Glacier
            Status: Enabled
            ExpirationInDays: !Ref ObjectExpirationInDays
            Transition:
              TransitionInDays: !Ref TransitionDaysForGlacier
              StorageClass: Glacier

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID:
                Fn::ImportValue:
                  !Sub "${AWS::AccountId}-${AWS::Region}-atomx-kms-key-arn"

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Id: PutObjPolicy
        Statement:
          - Sid:  DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal:
              AWS: !Sub "${AWS::AccountId}"
            Action: s3:PutObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref 'S3Bucket', '/*']]
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption-aws-kms-key-id':
                  Fn::ImportValue:
                    !Sub "${AWS::AccountId}-${AWS::Region}-atomx-kms-key-arn"
                's3:x-amz-server-side-encryption': 'aws:kms'

          - Sid: Enforce HTTPS Connections
            Action: s3:*
            Effect: Deny
            Principal:
              AWS: "*"
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref 'S3Bucket', '/*']]
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  SecuredBucketName:
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${ProjectPrefix}-${BucketName}-${AWS::AccountId}-${AWS::Region}